import { ReactNode } from "react"
import Head from "next/head"
import Footer from "./Footer"

type Props = {
  children?: ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col items-center justify-center py-2 font-kiwi bg-gray-100">
        <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
          {children}
        </main>
        <Footer /> 
      </div>
    </>
  );
}

export default Layout;