import { ReactNode } from "react"
import Head from "next/head"
import Footer from "./Footer"
import styles from '../styles/components/Layout.module.css'

type Props = {
  children?: ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          {children}
        </main>
        <Footer /> 
      </div>
    </>
  );
}

export default Layout;